### ISSUE TITLE
Possibble UI/UX improvments

### ISSUE THREAD

**Issue by sumanthyedoti** [angadgill92/angadgill.in#1]
- [x] reduce `box-shadow` of the card a little
- [x] do not overlap © and box-shadow
- [x] add padding around LinkedIn and Twitter logos a little
- [x] open external links on a new tab for better UX
- [ ] make the card width responsive and wrap the contact icons when the width is not sufficient on mobile
- [x] Profile zoom on hover may not be required

**Comment by angadgill92** [comment]
Thanks for the suggestions @sumanthyedoti 👍🏼
